// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251117090124_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Ai", b =>
                {
                    b.Property<int>("Aiid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("aiid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Aiid"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("Phonenumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phonenumber");

                    b.HasKey("Aiid")
                        .HasName("ai_pkey");

                    b.HasIndex(new[] { "Email" }, "ai_email_key")
                        .IsUnique();

                    b.ToTable("ai", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Airole", b =>
                {
                    b.Property<int>("Roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Roleid"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rolename");

                    b.HasKey("Roleid")
                        .HasName("airole_pkey");

                    b.HasIndex(new[] { "Rolename" }, "airole_rolename_key")
                        .IsUnique();

                    b.ToTable("airole", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Airolemapping", b =>
                {
                    b.Property<int>("Aiid")
                        .HasColumnType("integer")
                        .HasColumnName("aiid");

                    b.Property<int>("Roleid")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.Property<DateTime?>("Assignedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assignedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Aiid", "Roleid")
                        .HasName("airolemapping_pkey");

                    b.HasIndex("Roleid");

                    b.ToTable("airolemapping", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Airolemapping", b =>
                {
                    b.HasOne("Domain.Entities.Ai", "Ai")
                        .WithMany("Airolemappings")
                        .HasForeignKey("Aiid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("airolemapping_aiid_fkey");

                    b.HasOne("Domain.Entities.Airole", "Role")
                        .WithMany("Airolemappings")
                        .HasForeignKey("Roleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("airolemapping_roleid_fkey");

                    b.Navigation("Ai");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Ai", b =>
                {
                    b.Navigation("Airolemappings");
                });

            modelBuilder.Entity("Domain.Entities.Airole", b =>
                {
                    b.Navigation("Airolemappings");
                });
#pragma warning restore 612, 618
        }
    }
}
