// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .HasColumnType("json")
                        .HasColumnName("config");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Prompt")
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<string>("ReferenceResourceIds")
                        .HasColumnType("json")
                        .HasColumnName("reference_resource_ids");

                    b.Property<string>("ResultResourceIds")
                        .HasColumnType("json")
                        .HasColumnName("result_resource_ids");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("chats_pkey");

                    b.HasIndex("SessionId");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("SessionName")
                        .HasColumnType("text")
                        .HasColumnName("session_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("chat_sessions_pkey");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex(new[] { "UserId", "WorkspaceId", "CreatedAt", "Id" }, "chat_sessions_user_id_workspace_id_created_at_id_idx");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ImageTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aspect_ratio");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("integer")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("KieTaskId")
                        .HasColumnType("text")
                        .HasColumnName("kie_task_id");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("output_format");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<string>("ResultUrls")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_urls");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("image_tasks_pkey");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_image_tasks_correlation_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_image_tasks_user_id");

                    b.ToTable("image_tasks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("SocialMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("social_media_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("posts_pkey");

                    b.HasIndex(new[] { "UserId", "WorkspaceId", "CreatedAt" }, "ix_posts_user_workspace_created_at")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "WorkspaceId" }, "ix_posts_workspace_id");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PostAnalyticsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("analysis_payload_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformPostId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform_post_id");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("PostPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("post_payload_json");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<Guid>("SocialMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("social_media_id");

                    b.Property<string>("StatsPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_payload_json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("post_analytics_snapshots_pkey");

                    b.HasIndex(new[] { "UserId", "SocialMediaId", "PlatformPostId" }, "ux_post_analytics_snapshots_user_social_post")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "SocialMediaId", "RetrievedAt" }, "ix_post_analytics_snapshots_user_social_retrieved_at");

                    b.ToTable("post_analytics_snapshots", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PostMetricSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<long?>("CommentCount")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("ImpressionCount")
                        .HasColumnType("bigint")
                        .HasColumnName("impression_count");

                    b.Property<long?>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<string>("MetricWindow")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_window");

                    b.Property<Guid>("PostPublicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_publication_id");

                    b.Property<JsonDocument>("RawMetrics")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_metrics");

                    b.Property<long?>("ReachCount")
                        .HasColumnType("bigint")
                        .HasColumnName("reach_count");

                    b.Property<long?>("SaveCount")
                        .HasColumnType("bigint")
                        .HasColumnName("save_count");

                    b.Property<long?>("ShareCount")
                        .HasColumnType("bigint")
                        .HasColumnName("share_count");

                    b.Property<long?>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.Property<long?>("WatchTimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("watch_time_seconds");

                    b.HasKey("Id")
                        .HasName("post_metric_snapshots_pkey");

                    b.HasIndex(new[] { "CapturedAt" }, "ix_post_metric_snapshots_captured_at");

                    b.HasIndex(new[] { "PostPublicationId", "CapturedAt" }, "ix_post_metric_snapshots_publication_captured_at")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "PostPublicationId", "CapturedAt", "MetricWindow" }, "ux_post_metric_snapshots_publication_captured_window")
                        .IsUnique();

                    b.ToTable("post_metric_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_post_metric_snapshots_comment_count_nonnegative", "comment_count IS NULL OR comment_count >= 0");

                            t.HasCheckConstraint("ck_post_metric_snapshots_impression_count_nonnegative", "impression_count IS NULL OR impression_count >= 0");

                            t.HasCheckConstraint("ck_post_metric_snapshots_like_count_nonnegative", "like_count IS NULL OR like_count >= 0");

                            t.HasCheckConstraint("ck_post_metric_snapshots_metric_window", "metric_window IN ('hour', 'day', 'lifetime')");

                            t.HasCheckConstraint("ck_post_metric_snapshots_reach_count_nonnegative", "reach_count IS NULL OR reach_count >= 0");

                            t.HasCheckConstraint("ck_post_metric_snapshots_save_count_nonnegative", "save_count IS NULL OR save_count >= 0");

                            t.HasCheckConstraint("ck_post_metric_snapshots_share_count_nonnegative", "share_count IS NULL OR share_count >= 0");

                            t.HasCheckConstraint("ck_post_metric_snapshots_view_count_nonnegative", "view_count IS NULL OR view_count >= 0");

                            t.HasCheckConstraint("ck_post_metric_snapshots_watch_time_seconds_nonnegative", "watch_time_seconds IS NULL OR watch_time_seconds >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Entities.PostPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DestinationOwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_owner_id");

                    b.Property<string>("ExternalContentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_content_id");

                    b.Property<string>("ExternalContentIdType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_content_id_type");

                    b.Property<DateTime?>("LastMetricsSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_metrics_sync_at");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("PublishStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publish_status");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("SocialMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("social_media_id");

                    b.Property<string>("SocialMediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("social_media_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("post_publications_pkey");

                    b.HasIndex(new[] { "PostId", "CreatedAt" }, "ix_post_publications_post_created_at")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "PublishStatus", "LastMetricsSyncAt" }, "ix_post_publications_publish_status_last_metrics_sync_at");

                    b.HasIndex(new[] { "WorkspaceId", "PublishedAt" }, "ix_post_publications_workspace_published_at")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "SocialMediaType", "DestinationOwnerId", "ExternalContentId" }, "ux_post_publications_external_content")
                        .IsUnique();

                    b.ToTable("post_publications", null, t =>
                        {
                            t.HasCheckConstraint("ck_post_publications_external_content_id_type", "external_content_id_type IN ('post_id', 'publish_id')");

                            t.HasCheckConstraint("ck_post_publications_publish_status", "publish_status IN ('processing', 'published', 'failed')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.PostResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.HasKey("Id")
                        .HasName("post_resources_pkey");

                    b.HasIndex("PostId");

                    b.ToTable("post_resources", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SocialMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("SocialMediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("social_media_type");

                    b.Property<string>("TokenType")
                        .HasColumnType("text")
                        .HasColumnName("token_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("social_medias_pkey");

                    b.ToTable("social_medias", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VideoTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aspect_ratio");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("integer")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<string>("ResultUrls")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_urls");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VeoTaskId")
                        .HasColumnType("text")
                        .HasColumnName("veo_task_id");

                    b.HasKey("Id")
                        .HasName("video_tasks_pkey");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_video_tasks_correlation_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_video_tasks_user_id");

                    b.ToTable("video_tasks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workspace_name");

                    b.Property<string>("WorkspaceType")
                        .HasColumnType("text")
                        .HasColumnName("workspace_type");

                    b.HasKey("Id")
                        .HasName("workspaces_pkey");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Chat", b =>
                {
                    b.HasOne("Domain.Entities.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chats_session_id_fkey");
                });

            modelBuilder.Entity("Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("chat_sessions_workspace_id_fkey");
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.HasOne("Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("posts_workspace_id_fkey");
                });

            modelBuilder.Entity("Domain.Entities.PostMetricSnapshot", b =>
                {
                    b.HasOne("Domain.Entities.PostPublication", null)
                        .WithMany()
                        .HasForeignKey("PostPublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("post_metric_snapshots_post_publication_id_fkey");
                });

            modelBuilder.Entity("Domain.Entities.PostPublication", b =>
                {
                    b.HasOne("Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("post_publications_post_id_fkey");

                    b.HasOne("Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("post_publications_workspace_id_fkey");
                });

            modelBuilder.Entity("Domain.Entities.PostResource", b =>
                {
                    b.HasOne("Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("post_resources_post_id_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
